---
#- modify sys db ui.advisory.color { value "Green" }
#- modify sys db ui.advisory.color { value "Red" }   
#Green=prod/stable     Red=maintenance/warning     Blue=in deployment
      
- hosts: all
  any_errors_fatal: true
  connection: local
  gather_facts: false
  collections:
  - f5networks.f5_modules
  environment:
    https_proxy: ''
    http_proxy: ''
    
  vars:
    bigip_provider:
      user: "{{ user }}"
      password: "{{ password }}"
      server: "{{ ansible_host }}"
      server_port: 443
      validate_certs: false
      #no_f5_teem: yes
    is_active: "{{ bigip_gather_var.devices | selectattr('self', 'equalto', 'yes') | map(attribute='failover_state') | first == 'active' }}"
    failover_device_group: "{{ bigip_gather_var.device_groups | selectattr('type', 'equalto', 'sync-failover')  | map(attribute='name') | first | default ('None') }}"

  tasks:
  - name: Gather facts (f5)
    bigip_device_info:
      provider: "{{ provider }}"
      gather_subset:
        - system-info
        - devices
    register: dev_fact
  
  - name: This can be used to print all facts
    debug:
      var: dev_fact
