---

- hosts: all
  any_errors_fatal: true
  connection: local
  gather_facts: false
  collections:
  - f5networks.f5_modules
  environment:
    https_proxy: ''
    http_proxy: ''
    
  vars:
    bigip_provider:
      user: "{{ user }}"
      password: "{{ password }}"
      server: "{{ ansible_host }}"
      server_port: 443
      validate_certs: false
      no_f5_teem: yes
    is_active: "{{ bigip_gather_var.devices | selectattr('self', 'equalto', 'yes') | map(attribute='failover_state') | first == 'active' }}"
    failover_device_group: "{{ bigip_gather_var.device_groups | selectattr('type', 'equalto', 'sync-failover')  | map(attribute='name') | first | default ('None') }}"

  tasks:
  - name: Get bigip config Information
    bigip_device_info:
      gather_subset: 
      - system-info
      - devices
      - device-groups
      provider: "{{ bigip_provider }}"
    register: bigip_gather_var
    retries: 3
    delay: 3
    
  #- name: This can be used to print facts
  #  debug:
  #    var: bigip_gather_var
  
  - name: This can be used to print facts
    debug:
      var: bigip_gather_var['devices'][0]['hostname']

  - name: This can be used to print facts
    debug:
      var: bigip_gather_var['system_info']['marketing_name']

  - name: This can be used to print facts
    debug:
      var: bigip_gather_var['system_info']['product_version']

  - name: This can be used to print facts
    debug:
      var: bigip_gather_var['system_info']['platform']

  - name: This can be used to print facts
    debug:
      var: bigip_gather_var['system_info']['chassis_serial']

  - name: This can be used to print facts
    debug:
      var: bigip_gather_var['devices'][0]['software_version']

  - name: This can be used to print facts
    debug:
      var: bigip_gather_var['devices'][0]['platform_id']
      
  #- name: Task3.1 - Capture Service Check Date
  #  shell: tmsh show sys version | grep "  Version" | awk '{print $2}'
  #  register: code_version
  #  tags: code
  #  
  #- name: Print code version
  #  debug:
  #    var: code_version
  
