---
      
- name: Multi-Test1
  hosts: all
  any_errors_fatal: true
  connection: local
  gather_facts: false
  collections:
  - f5networks.f5_modules
  environment:
    https_proxy: ''
    http_proxy: ''
    
  vars:
    user: admin
    password: "{{ password }}"
    bigip_provider:
      server: "{{ ansible_host }}"
      user: admin
      password: "{{ password }}"
      server_port: 443
      validate_certs: false
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"

    
  tasks:
  - name: Gather facts (f5)
    bigip_device_info:
      provider: "{{ provider }}"
      gather_subset:
        - system-info
        - devices
    register: dev_fact
  
  - name: This can be used to print all facts
    debug:
      var: dev_fact
