---

- name: Get bigip config Information
  bigip_device_info:
    gather_subset: 
    - system-info
    - devices
    - device-groups
    provider: "{{ bigip_provider }}"
  register: bigip_gather_var
  retries: 3
  delay: 3
  
#- name: This can be used to print facts
#  debug:
#    var: bigip_gather_var

- name: This can be used to print facts
  debug:
    var: bigip_gather_var['devices'][0]['hostname']
- name: This can be used to print facts
  debug:
    var: bigip_gather_var['system_info']['marketing_name']

- name: This can be used to print facts
  debug:
    var: bigip_gather_var['system_info']['product_version']

- name: This can be used to print facts
  debug:
    var: bigip_gather_var['system_info']['platform']

- name: This can be used to print facts
  debug:
    var: bigip_gather_var['system_info']['chassis_serial']

- name: This can be used to print facts
  debug:
    var: bigip_gather_var['devices'][0]['software_version']

#- name: This can be used to print facts
#  debug:
#    var: bigip_gather_var['devices'][0]['platform_id']
#    
#- name: Task3.1 - Capture Service Check Date
#  shell: tmsh show sys version | grep "  Version" | awk '{print $2}'
#  register: code_version
#  tags: code
#  
#- name: Print code version
#  debug:
#    var: code_version
  
